plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'io.github.kachaya.skk'
    compileSdk 36

    defaultConfig {
        applicationId "io.github.kachaya.skk"
        minSdk 28
        targetSdk 31
        versionCode 10101
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            // 出力ファイル名を "AndroidSKK-1.0.0.apk" に変更する設定
            applicationVariants.all { variant ->
                variant.outputs.all { output ->
                    def project = "AndroidSKK"
                    def version = variant.versionName
                    outputFileName = "${project}-${version}.apk"
                }
            }
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lint {
        // targetSdkVersion 33以上を求めるチェック(ExpiredTargetSdkVersion)を無視します
        disable 'ExpiredTargetSdkVersion'
        // リリースビルド時のチェックでエラーが出ても中断しない
        checkReleaseBuilds false
        abortOnError false
    }

    buildFeatures {
        buildConfig true // BuildConfigクラスの生成を明示的に有効化
    }
}

dependencies {
    implementation files('libs/jdbm-1.0.jar')
    implementation libs.appcompat
    implementation libs.material
    implementation libs.preference
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}